% Routine eegplot.m
% Auxiliary routine to render a pretty plot for EEG data.
% Called by selseg.m

if Kch <= length(Ch),
   set(gca,'Visible', 'off', ...
      'XTick',[], ...
      'XColor',[1 1 1], ...
      'XTickLabel',[], ...
      'YTick',[], ...
      'YColor',[1 1 1], ...
      'YTickLabel',[]);
   if exist('ID_CHANNEL')==1,
      %['Ch. ' num2str(Ch(Kch)) ' (' deblank2(ID_CHANNEL(Ch(Kch)+1,:)) ')']
      ht=text(V_TIME0-(V_TIME1-V_TIME0)*7.5/80,0, ...
         [Ch(Kch)]);
   else % This is for testing purpose only.
      ht=text(V_TIME0-(V_TIME1-V_TIME0)*7.5/80,0, ...
         [Ch(Kch)]);
   end;
   
   set(ht,'HorizontalAlignment', 'center', ...
      'Color',[0 0 0],... % ['Color',colorscl(Kch,length(Ch))]
      'Visible','on', ...
      'FontAngle','normal', ...
      'FontWeight','bold', ...
      'FontSize', [16])
   
else
   set(gca,'FontAngle','normal', ...
      'Box', 'off', ...
      'TickDir', 'in', ...
      'Ytick',[], ...
      'YColor',[1 1 1], ...
      'YTickLabel',[], ...
      'FontSize',[16], ...
      'FontWeight','bold');
end;
